Episode4 LLM
carpentries-incubator/Natural-language-processing pull request #29
Opened 2024-12-19 16:08 UTC by laurasootes

This is the LLM episode that Thijs and I wrote.

@ThijsVroegh : can you check if all the code works?

2024-12-23 11:28 UTC, n400peanuts requested changes
I think the lesson is very nice and it covers a lot of content! I would suggest adding more exercises and perhaps adding links and mentions to extra material so that people can go and take a look it autonoumously.

Mayor comments for me are: (1) what is a RAG and how does it relate to a RAG agent is not clear and (2) adding info re- what is a vector store, how does a retrieval work and chunking strategies are necessary info

the rest are all minor things! 

congrats on the episode!

2024-12-23 11:28 UTC, n400peanuts commented on episodes/03-LargeLanguageModels.md
> +In general, a bigger version of the same model (such as Llama3.1:70b) is better in accuracy, but since it is larger it takes more resources to run and can hence be too much for a laptop.
Maybe we can find another wod for mentioning the performance of the models, and how does a smaller model compares with a bigger one. I fear that saying `accuracy` may lead to touching upon a whole chapter about how to evaluate these models, and what does it mean good performance in the context of a particular task. The are several metrics and actually smaller models are "better" than bigger models in some tasks. So my suggestion is to not mention this altogether, or to give more context and more explanations about what you consider more accurate in this context

```suggestion
In general, a bigger version of the same model (such as Llama3.1:70b) is better in accuracy, but since it is larger it takes more resources to run and can hence be too much for a laptop.
```

```suggestion

```

2024-12-23 11:28 UTC, n400peanuts commented on episodes/03-LargeLanguageModels.md
> +Create a model instance. Here, `model` defines the LLM to be used, which is set to the model just downloaded, and `temperature` sets the randomness of the mode, using the value zero ensures that repe
```suggestion
## Create a model instance. 

Here, `model` defines the LLM to be used, which is set to the model just downloaded, and `temperature` sets the randomness of the mode, using the value zero ensures that repeating a question will give the same model output (answer).
```

2024-12-23 11:28 UTC, n400peanuts commented on episodes/03-LargeLanguageModels.md
> +### Use the chat history
love this! beautiful!

2024-12-23 11:28 UTC, n400peanuts commented on episodes/03-LargeLanguageModels.md
> +The package LangGraph is a library that is designed to build LLM agents using workflows represented as graphs. The workflows you create consist of connected components, which allows you to build mult
This makes me think that you use langgraph already in some tasks above, and might be useful to mention right at the beginning (when you introduce ollama) that you will use also langgraph?

2024-12-23 11:28 UTC, n400peanuts commented on episodes/03-LargeLanguageModels.md
> +Define an memory id for the current conservation.
just a typo

```suggestion
Define a memory id for the current conservation.
```

2024-12-23 11:28 UTC, n400peanuts commented on episodes/03-LargeLanguageModels.md
> +output["messages"][-1].pretty_print()
You can add the output of the pretty_print() in the markdown, by enclosing it in: ``

2024-12-23 11:28 UTC, n400peanuts commented on episodes/03-LargeLanguageModels.md
> +output["messages"][-1].pretty_print()
I think it's nice to add the output rendered in the markdown page because it allows any instructor to see if he/she gets the same output structure (of course the answer will always be different)

2024-12-23 11:28 UTC, n400peanuts commented on episodes/03-LargeLanguageModels.md
> +A chatbot tends to give quite generalised answers. A more specific chatbot can be made by building a Retrieval Augmented Generation agent. This is an information that you yourself provide with a know
I think you may mean 'generic'
```suggestion
A chatbot tends to give quite generic answers. A more specific chatbot can be made by building a Retrieval Augmented Generation agent. This is an information that you yourself provide with a knowledge base: a large number of documents. When prompted with a questions, the agent first retrieves relevant sections of the data that is in the knowledge base, and then generates and answer based on that data. In this way you can build an agent with very specific knowledge.
```

2024-12-23 11:28 UTC, n400peanuts commented on episodes/03-LargeLanguageModels.md
> +A chatbot tends to give quite generalised answers. A more specific chatbot can be made by building a Retrieval Augmented Generation agent. This is an information that you yourself provide with a know
I fear here that without introducing what is a RAG, what does generation stand for in this context we may make the mistake of thinking that an agent/chatbot is a RAG, while instead these are two different concepts.

I like the way AWS explains it, maybe useful to disentangle both? https://aws.amazon.com/what-is/retrieval-augmented-generation/

2024-12-23 11:28 UTC, n400peanuts commented on episodes/03-LargeLanguageModels.md
> +```python
I think we need here some level of detail (with a callout perhaps?) re- chunking and the effect that it has on the retrieval efficiency. There are many different chunking strategies and even optimisation procedures to make sure that one not only chooses the appropriate chunking method, but also that this is optimised for the specific input. Also, embedding models have a role in this particular step so I would suggest adding some callout with relevant material to at least acknowledge that these are important topics and one needs to carefully assess each one of them to make sure to build a reliable RAG agent

2024-12-23 11:28 UTC, n400peanuts commented on episodes/03-LargeLanguageModels.md
> +```python
I am not sure which resources could be helpful to investigate better this, but this is what I used as starting point for our MINE-DD rag: 

- https://js.langchain.com/docs/how_to/extraction_long_text/#common-issues
- https://community.openai.com/t/how-to-optimize-text-chunking-for-improved-embedding-vectorization/380369
- https://community.openai.com/t/automating-chunking-for-customized-gpt-knowledge-in-vector-databases/729625/4
- https://zilliz.com/blog/experimenting-with-different-chunking-strategies-via-langchain
- https://towardsdatascience.com/rag-101-chunking-strategies-fdc6f6c2aaec

2024-12-23 11:28 UTC, n400peanuts commented on episodes/03-LargeLanguageModels.md
> +:::::::::::: challenge
Is this meant to be left empty?

2024-12-23 11:28 UTC, n400peanuts commented on episodes/03-LargeLanguageModels.md
> +## Key points to remember
This is a specific flag in carpentries that could be helpful!

```suggestion
::::::::::::::::::::::::::::::::::::: keypoints
```

2024-12-23 11:28 UTC, n400peanuts commented on episodes/03-LargeLanguageModels.md
> +
```suggestion
:::::::::::::::::::::::::::::::::::::
```

2025-01-06 09:23 UTC, laurasootes commented on episodes/03-LargeLanguageModels.md
> +Training a large language model is extremely resource intensive; while you can train for example a simple classifier to identify if a sentence is positive or negative yourself, this is not possible f
I am not sure what previous section you refer to that is repeated?

The take-home message I was trying to convey was mainly to realise how huge the environmental impact is from training, but also in using the model (like we saw recently in our meeting, people don't always realise that for example when you are using chatgpt, this is not on your pc but in some datacenter because your computer wouldn't be able to handle it. And even on our cluster with the A100 it takes very long). So mainly just to pause for a moment to consider the fact that it's fun and usefull and all, but has environmental consequences. 

I rephrased and shortened it a bit, merging your suggestion and mine. Do you still think it is best to put it in a callout?

2025-01-06 12:49 UTC, n400peanuts commented on episodes/03-LargeLanguageModels.md
> +Training a large language model is extremely resource intensive; while you can train for example a simple classifier to identify if a sentence is positive or negative yourself, this is not possible f
I think mine was a suggestion but if you think that your changes accomplish the same thing or are better it's fine by me!

2025-01-07 14:13 UTC, ThijsVroegh commented on episodes/03-LargeLanguageModels.md
> +llm = ChatOllama(model=llama3.1:8b, temperature=0)
llm = ChatOllama(model="llama3.1:8b", temperature=0)

2025-01-07 14:15 UTC, ThijsVroegh commented on episodes/03-LargeLanguageModels.md
> +
Do we need to give a solution here, or at least a brief answer? Right now, clicking on it leads to an empty box.

2025-01-07 14:21 UTC, ThijsVroegh commented on episodes/03-LargeLanguageModels.md
> +output = app.invoke({"messages": input_messages}, config)
output = graph.invoke({"messages": input_messages}, config)

2025-01-07 14:24 UTC, ThijsVroegh commented on episodes/03-LargeLanguageModels.md
> +dir = "./rag_data"
```suggestion
import os
pwd = os.getcwd()
print(pwd)

dir = os.path.join(os.getcwd(), "rag_data")
print(dir)

if os.path.exists(dir) and os.path.isdir(dir):
    print(f"Directory {dir} exists.")
else:
    print(f"Directory {dir} does not exist.")
```

2025-01-07 14:25 UTC, ThijsVroegh commented on episodes/03-LargeLanguageModels.md
> +output = app.invoke({"messages": input_messages}, config)
```suggestion
output = graph.invoke({"messages": input_messages}, config)
```

2025-01-07 14:26 UTC, ThijsVroegh commented on episodes/03-LargeLanguageModels.md
> +llm = ChatOllama(model=llama3.1:8b, temperature=0)
```suggestion
llm = ChatOllama(model="llama3.1:8b", temperature=0)
```

2025-01-07 14:34 UTC, ThijsVroegh commented on episodes/03-LargeLanguageModels.md
> +vectorstore = InMemoryVectorStore.from_texts(
Add that this can take some time, so be patient..

2025-01-07 14:37 UTC, ThijsVroegh commented on episodes/03-LargeLanguageModels.md
> +This is quite a specific answer. It can be seen why by looking at the text snippets that were used:
I got as an answer:

The user's question is not provided. However, based on the given context, I can infer a possible question that might be relevant.

Here are a few possibilities:

1. Who predicted colonisation of the moon?
Answer: Gordon Cooper, a former American astronaut.

2. What was the reason for colonising the moon according to Gordon Cooper?
Answer: To combat over-population on earth and severe food shortages.

3. Where did Luna-24 land on the moon?
Answer: In the south-eastern part of the Sea of Crisis.

Please provide the actual question so I can give a more accurate answer.

Obviously, asking who landed on the Moon? is a very specific question. Perhaps avoid saying "This is quite a specific answer"?

2025-01-15 11:19 UTC, merged